language: python
python:
  - 3.7

install:
  - pip install --upgrade pip
  - pip install codecov coverage isort flake8
  - pip install cython

script:
 - pip install black; black --check .
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff *.py haggregate tests
 - coverage run --include="./*" --omit="docs/","*/tests/*","*/tests.py","setup.py" ./setup.py test

after_success:
  - codecov
